language: c

sudo: false

before_install:
  - mkdir -p $HOME/build/git
  - pwd
  - git archive --format=tar HEAD | tar --skip-old-files -C $HOME/build/git -xf -
  - pushd $HOME/build/git

install:
  - pwd
  - make -j4

script:
  - pwd
  - cd t/
  - prove --timer -j4 ./t[0-9]*.sh

cache:
  directories:
    - $HOME/build/git

