language: c

sudo: false

before_install:
  - if [ ! -d $HOME/build/git ]; then git clone ./ $HOME/build/git; fi
  - pushd $HOME/build/git
  - git fetch origin && git checkout -f origin/${TRAVIS_BRANCH}

install:
  - make -j4

script:
  - cd t/
  - prove --timer -j8 ./t[0-9]*.sh

cache:
  directories:
    - $HOME/build/git

