language: c

sudo: false

before_install:
  - ORIGIN_DIR=`pwd`
  - "[ -d $HOME/build/git/.git ] || git clone --depth=50 ./ $HOME/build/git"
  - pushd $HOME/build/git
  - git remote -v
  - git remote remove origin || exit 0
  - git remote add origin ${ORIGIN_DIR}
  - ls -lha 
  - ls -lha ${ORIGIN_DIR}
  - git remote -v
  - git branch -a
  - git status
  - git fetch origin
  - git branch -a
  - git status
  - git fetch origin && git checkout -f ${TRAVIS_BRANCH} && git reset --hard ${TRAVIS_BRANCH}
  - git branch -a
  - git status
  - |
    git ls-files -z | xargs -P4 -0 -I{} bash -c "
      echo \"FILE={}\";
      TIME=$(git log --pretty=format:%ci -n1 \"{}\");
      TIME=$(date +%y%m%d%H%M.%S --date \"$TIME\");
      touch -t $TIME \"{}\"
    "

install:
  - make -j4

script:
  - cd t/
  - prove --timer -j8 ./t[0-9]*.sh

cache:
  directories:
    - $HOME/build/git

