language: c

sudo: false

before_install:
  - "[ -d $HOME/build/git/.git ] || git clone git://github.com/sh19910711/git.git $HOME/build/git"
  - pushd $HOME/build/git
  - git fetch origin && git checkout -f ${TRAVIS_BRANCH} && git reset --hard ${TRAVIS_BRANCH}
  - |
    git ls-files -z | while read -r -d '' FILE; do
      TIME1=$(git log --pretty=format:%ci -n1 "$FILE");
      TIME2=$(date +%y%m%d%H%M.%S --date "$TIME1");
      touch -mt $TIME2 $FILE;
      echo "touch -at $TIME2 $FILE";
    done

install:
  - make -j4

script:
  - cd t/
  - prove --timer -j8 ./t[0-9]*.sh

cache:
  directories:
    - $HOME/build/git

