language: c

sudo: false

before_install:
  - mkdir -p $HOME/build-git
  - pwd
  - rsync -avr `git ls-files` $HOME/build-git
  - pushd $HOME/build-git

install:
  - pwd
  - make -j4

script:
  - pwd
  - make test

cache:
  - $HOME/build-git

