language: c

sudo: false

before_install:
  - "[ -d $HOME/build/git ] || git clone ./ $HOME/build/git"
  - pushd $HOME/build/git
  - git fetch origin && git checkout -f ${TRAVIS_BRANCH} && git reset --hard ${TRAVIS_BRANCH}
  - git status
  - |
    for FILE in $(git ls-files); do
      TIME=$(git log --pretty=format:%ci -n1 $FILE)
      TIME=$(date +%y%m%d%H%M.%S --date "$TIME")
      touch -t $TIME $FILE
    done

install:
  - make -j4

script:
  - cd t/
  - prove --timer -j8 ./t[0-9]*.sh

cache:
  directories:
    - $HOME/build/git

