language: c

sudo: false

before_install:
  - mkdir -p $HOME/build
  - "[ -d $HOME/build/git/.git ] || git clone git://github.com/sh19910711/git.git $HOME/build/git"
  - pushd $HOME/build/git
  - stat userdiff.c
  - if [ -f userdiff.o ]; then stat userdiff.o; fi
  - git fetch origin && git checkout -f ${TRAVIS_BRANCH} && git reset --hard ${TRAVIS_BRANCH}
  - |
    git ls-files -z | while read -r -d '' FILE; do
      TIME1=$(git log --pretty=format:%ci -n1 "$FILE");
      TIME2=$(date +%y%m%d%H%M.%S --date "$TIME1");
      touch -t $TIME2 $FILE;
    done
  - git diff-tree --no-commit-id --name-only HEAD
  - |
    git diff-tree -z --no-commit-id --name-only HEAD | while read -r -d '' FILE; do
      echo touch $FILE
      touch $FILE
    done
  - stat userdiff.c
  - if [ -f userdiff.o ]; then stat userdiff.o; fi

install:
  - make -j4
  - stat userdiff.c
  - if [ -f userdiff.o ]; then stat userdiff.o; fi

script:
  - pushd t/
  # - prove --timer -j8 ./t[0-9]*.sh
  - popd

cache:
  directories:
    - $HOME/build/git

